/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/scene.glb -K 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterSpot" position={[0, 0.088, -0.921]} rotation={[Math.PI, -0.047, Math.PI]} scale={0.68}>
          <group name="Armature">
            <primitive object={nodes.Hips} />
          </group>
          <skinnedMesh name="Wolf3D_Body" geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
          <skinnedMesh name="Wolf3D_Hair" geometry={nodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Wolf3D_Hair.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Bottom" geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Footwear" geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Top" geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
          <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} />
          <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} />
          <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} />
          <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} />
        </group>
        <group name="Bonsai" position={[1.529, 0.601, -1.699]}>
          <mesh name="mesh430673059" geometry={nodes.mesh430673059.geometry} material={materials.mat17} />
          <mesh name="mesh430673059_1" geometry={nodes.mesh430673059_1.geometry} material={materials.mat11} />
          <mesh name="mesh430673059_2" geometry={nodes.mesh430673059_2.geometry} material={materials.mat20} />
          <mesh name="mesh430673059_3" geometry={nodes.mesh430673059_3.geometry} material={materials.mat10} />
          <mesh name="mesh430673059_4" geometry={nodes.mesh430673059_4.geometry} material={materials.mat8} />
          <mesh name="mesh430673059_5" geometry={nodes.mesh430673059_5.geometry} material={materials.mat25} />
          <mesh name="mesh430673059_6" geometry={nodes.mesh430673059_6.geometry} material={materials.mat15} />
          <mesh name="mesh430673059_7" geometry={nodes.mesh430673059_7.geometry} material={materials.mat16} />
        </group>
        <group name="Desktop" position={[0, 0.556, -1.287]} rotation={[0, 1.55, 0]}>
          <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={materials['mat20.001']} />
          <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat23} />
          <mesh name="Node-Mesh_2" geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat22} />
          <mesh name="Node-Mesh_3" geometry={nodes['Node-Mesh_3'].geometry} material={materials['mat17.001']} />
          <mesh name="Node-Mesh_4" geometry={nodes['Node-Mesh_4'].geometry} material={materials['mat8.001']} />
        </group>
        <group name="Orchid" position={[-1.501, -0.032, 1.683]} rotation={[Math.PI, -0.239, Math.PI]}>
          <mesh name="Deps" geometry={nodes.Deps.geometry} material={materials.Color_1} />
          <mesh name="Deps_1" geometry={nodes.Deps_1.geometry} material={materials.Color_2} />
        </group>
        <group name="Scooter" position={[-0.017, 0.272, -1.051]} rotation={[0, 1.554, 0]}>
          <mesh name="Node-Mesh001" geometry={nodes['Node-Mesh001'].geometry} material={materials.Floor} />
          <mesh name="Node-Mesh001_1" geometry={nodes['Node-Mesh001_1'].geometry} material={materials.mat21} />
          <mesh name="Node-Mesh001_2" geometry={nodes['Node-Mesh001_2'].geometry} material={materials['mat23.001']} />
          <mesh name="Node-Mesh001_3" geometry={nodes['Node-Mesh001_3'].geometry} material={materials['mat22.001']} />
          <mesh name="Node-Mesh001_4" geometry={nodes['Node-Mesh001_4'].geometry} material={materials.mat14} />
          <mesh name="Node-Mesh001_5" geometry={nodes['Node-Mesh001_5'].geometry} material={materials['mat25.001']} />
          <mesh name="Node-Mesh001_6" geometry={nodes['Node-Mesh001_6'].geometry} material={materials.mat13} />
          <mesh name="Node-Mesh001_7" geometry={nodes['Node-Mesh001_7'].geometry} material={materials.mat24} />
          <mesh name="Node-Mesh001_8" geometry={nodes['Node-Mesh001_8'].geometry} material={materials['mat8.002']} />
          <mesh name="Node-Mesh001_9" geometry={nodes['Node-Mesh001_9'].geometry} material={materials.mat12} />
          <mesh name="Node-Mesh001_10" geometry={nodes['Node-Mesh001_10'].geometry} material={materials['mat10.001']} />
        </group>
        <group name="Plane">
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.Floor} />
          <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials.Walls} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.glb')
