/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/scene.gltf 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import {motion} from "framer-motion-3d"
import * as THREE from 'three'
import { animate, useMotionValue } from 'framer-motion'
import { useFrame } from '@react-three/fiber'
export function Office(props) {
  const {section}=props
  const { nodes, materials } = useGLTF('models/scene.glb')
  const texture= useTexture('textures/baked.jpg')
  texture.flipY=false
  texture.encoding=THREE.sRGBEncoding

  const textureMaterial= new THREE.MeshStandardMaterial({
    map:texture,
    transparent:true,
    opacity:1,
  })

  const textureOpacity=useMotionValue(0);

  useEffect(()=>{
    animate(textureOpacity, section === 0 ? 1 : 0.9)
  },[section])

  useFrame(()=>{
    textureMaterial.opacity=textureOpacity.get();
  })
  return (
    <group {...props} dispose={null}>
    <motion.group 
      scale={[0,0,0]}
      animate={{
        scale: section === 0 ? 1 : 0.9
      }}
      name="Bonsai" 
      position={[1.529, 0.601, -1.699]}
    >
      <mesh name="mesh430673059" geometry={nodes.mesh430673059.geometry} material={textureMaterial} />
      <mesh name="mesh430673059_1" geometry={nodes.mesh430673059_1.geometry} material={textureMaterial} />
      <mesh name="mesh430673059_2" geometry={nodes.mesh430673059_2.geometry} material={textureMaterial} />
      <mesh name="mesh430673059_3" geometry={nodes.mesh430673059_3.geometry} material={textureMaterial} />
      <mesh name="mesh430673059_4" geometry={nodes.mesh430673059_4.geometry} material={textureMaterial} />
      <mesh name="mesh430673059_5" geometry={nodes.mesh430673059_5.geometry} material={textureMaterial} />
      <mesh name="mesh430673059_6" geometry={nodes.mesh430673059_6.geometry} material={textureMaterial} />
      <mesh name="mesh430673059_7" geometry={nodes.mesh430673059_7.geometry} material={textureMaterial} />
    </motion.group>
    <motion.group 
      scale={[0,0,0]}
      animate={{
        scale: section === 0 ? 1 : 0.9,
      }}
      name="Desktop" 
      position={[0, 0.556, -1.287]} 
      rotation={[0, 1.55, 0]}>
      <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh_2" geometry={nodes['Node-Mesh_2'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh_3" geometry={nodes['Node-Mesh_3'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh_4" geometry={nodes['Node-Mesh_4'].geometry} material={textureMaterial} />
    </motion.group>
    <group name="Orchid" position={[-1.501, -0.032, 1.683]} rotation={[Math.PI, -0.239, Math.PI]}>
      <mesh name="Deps" geometry={nodes.Deps.geometry} material={textureMaterial} />
      <mesh name="Deps_1" geometry={nodes.Deps_1.geometry} material={textureMaterial} />
    </group>
    <motion.group 
      scale={[0,0,0]}
      animate={{
        scale: section === 0 ? 1 : 0.9,
      }}
      name="Scooter" 
      position={[-0.017, 0.272, -1.051]} 
      rotation={[0, 1.554, 0]}>
      <mesh name="Node-Mesh001" geometry={nodes['Node-Mesh001'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh001_1" geometry={nodes['Node-Mesh001_1'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh001_2" geometry={nodes['Node-Mesh001_2'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh001_3" geometry={nodes['Node-Mesh001_3'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh001_4" geometry={nodes['Node-Mesh001_4'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh001_5" geometry={nodes['Node-Mesh001_5'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh001_6" geometry={nodes['Node-Mesh001_6'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh001_7" geometry={nodes['Node-Mesh001_7'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh001_8" geometry={nodes['Node-Mesh001_8'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh001_9" geometry={nodes['Node-Mesh001_9'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh001_10" geometry={nodes['Node-Mesh001_10'].geometry} material={textureMaterial} />
    </motion.group>
    <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={textureMaterial} />
    <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={textureMaterial} />
  </group>
  )
}

useGLTF.preload('models/scene.glb')
